"""Evaluation passes for every finished run, one per registered evaluation pass.

    uv run python scripts/evaluate_grid.py                                   # runs/, every pass, 32 seeds
    uv run python scripts/evaluate_grid.py --root runs/_smoke_post --n-eval-seeds 4 --passes stochastic argmax
    uv run python scripts/evaluate_grid.py --passes all --conditions A-S1-N9 --seeds 0

Passes (``--passes``), each resumable per (run, pass) through ``<run_dir>/eval/manifest.json``:

  stochastic   the primary pass: the selected checkpoint, stochastic action sampling, the 32
               evaluation seeds, ``hamlet.evaluate.evaluate`` unchanged, into
               ``<run_dir>/eval/stochastic/<condition>/<ckpt>/seed<k>_ep0.parquet`` (the layout
               ``scripts/report_pilot.py`` already writes, so the pilot's evaluation is reused).
  argmax       the secondary pass: the same seeds and columns with greedy decoding through
               ``hamlet.evaluate.evaluate(..., mode="argmax")`` (the argmax of the policy's own
               log-probability vector; ``ArgmaxPolicy`` here is the same computation as a wrapper and
               is used only on a tree without that parameter); the Parquet's ``checkpoint`` column
               carries ``<ckpt>_argmax`` so the mode is visible in the data.
  shocks       ``jobs_closed_d4`` (H1c primary) and ``energy_x2_d4`` (the promotion) on every condition,
               each paired with the unshocked stochastic pass on the same seed; the plan names arm A
               (``scope: plan``), the others are run and marked ``scope: superset``. The GREEDY-CLOCK
               reference is shocked too (``<root>/<condition>-<shock>/GREEDY-CLOCK/``).
  init         evaluation-time initial-state dispersion narrow (0.70, 0.80) and wide (0.25, 1.00) on
               A-S0-N<N> and A-S1-N<N> (default (0.50, 1.00) is the stochastic pass itself), condition
               labelled ``<condition>-init_<name>`` in the Parquet.
  swap         on every S1 condition: 4,096 observations sampled uniformly from the seed's own
               stochastic evaluation episodes (regenerated by replaying the same episodes; observations
               are not logged), ``hamlet.metrics.specialisation.swap_test`` for every kind in
               ``SWAP_KINDS`` with a bootstrap over observations, written to
               ``<run_dir>/eval/swap/swap.json``; and the replay counts of the
               ``trait_and_home_shuffle`` DOL null (``hamlet.evaluate.trait_and_home_shuffle_counts``,
               full rollouts, so capped by ``--replay-perm`` and ``--replay-seeds``, both recorded) to
               ``<run_dir>/eval/swap/trait_home_shuffle.npz``.

The per-run manifest records, per pass: mode, seeds, checkpoint path, git describe and commit, the
condition written, scope (plan or superset), file count, and timestamps. Nothing under ``hamlet/``
is edited by this script; every rollout goes through ``hamlet.evaluate.rollout``/``evaluate`` and
every metric through ``hamlet.metrics``.
"""
from __future__ import annotations

import argparse
import dataclasses
import inspect
import json
import os
import sys
import time
from pathlib import Path
from typing import Any, Callable, Optional, Sequence

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from hamlet.config import HamletConfig  # noqa: E402
import analysis_constants as K  # noqa: E402
from hamlet.core import HamletCore  # noqa: E402
from hamlet.evaluate import (  # noqa: E402
    NO_CHECKPOINT,
    episode_path,
    episode_rng,
    evaluate,
    evaluation_seeds,
    make_policy,
    trait_and_home_shuffle_counts,
)
from hamlet.metrics.common import DEFAULTS  # noqa: E402
from hamlet.metrics.specialisation import SWAP_KINDS, swap_test  # noqa: E402
from hamlet.policies import GreedyClockPolicy  # noqa: E402
from hamlet.train_common import git_provenance, utc_now  # noqa: E402

PASSES = ("stochastic", "argmax", "shocks", "init", "swap")
SHOCKS = ("jobs_closed_d4", "energy_x2_d4")
INIT_RANGES = {"narrow": (0.70, 0.80), "wide": (0.25, 1.00)}          # default (0.50, 1.00) = the stochastic pass
# Condition names carry the population size and follow the run root: main() rebinds
# INIT_CONDITIONS once --root is known, so an archived root at another N is read under its own names.
_NN = HamletConfig().n_agents
INIT_CONDITIONS = (f"A-S0-N{_NN}", f"A-S1-N{_NN}")
SHOCK_PLAN_ARMS = ("A",)
SWAP_SAMPLE = 4_096
SWAP_STREAM = 9
REPLAY_STREAM = 10


# ---------------------------------------------------------------------------------------------- policies
class ArgmaxPolicy:
    """Greedy decoding of a learned policy: the argmax of its own log-probability vector.

    ``inner.act`` returns sampled actions and the full ``(N, N_ACTIONS)`` log-probability
    matrix; the argmax of that matrix equals the argmax of the network's logits, so this
    wrapper changes only the action choice and leaves the world's random stream untouched.
    ``rng`` is kept so ``hamlet.evaluate.rollout`` can reseed it per episode as it does for
    every learned policy; the argmax never draws from it.
    """

    def __init__(self, inner, name: Optional[str] = None) -> None:
        self.inner = inner
        self.rng = getattr(inner, "rng", np.random.default_rng(0))
        self.name = name or f"{inner.name}-argmax"

    def act(self, obs: np.ndarray, core: HamletCore):
        _, log_probs = self.inner.act(obs, core)
        return np.argmax(log_probs, axis=1).astype(np.int64), log_probs


def observation_batch(cfg: HamletConfig, policy, seeds: Sequence[int], rng: np.random.Generator,
                      n_sample: int = SWAP_SAMPLE) -> tuple[np.ndarray, np.ndarray]:
    """``n_sample`` observations drawn uniformly from replays of the seeds' stochastic episodes, plus the trait vectors.

    Observations are not logged, so the episodes are replayed with the same world and
    policy streams ``hamlet.evaluate.rollout`` uses (``episode_rng(seed, 0)`` for both).
    """
    per_seed = int(np.ceil(n_sample / len(seeds)))
    chunks, traits = [], None
    for seed in seeds:
        core = HamletCore(cfg, seed, traits_seed=seed)
        core.rng = episode_rng(seed, 0)
        obs = core.reset(None)
        if hasattr(policy, "rng"):
            policy.rng = episode_rng(seed, 0)
        rows = np.empty((cfg.episode_ticks, cfg.N, cfg.obs_dim), dtype=np.float32)
        for t in range(cfg.episode_ticks):
            rows[t] = obs
            actions, _ = policy.act(obs, core)
            obs, _, _ = core.step(actions)
        flat = rows.reshape(-1, cfg.obs_dim)
        chunks.append(flat[rng.choice(flat.shape[0], size=per_seed, replace=False)])
        traits = core.traits.to_vectors()
    batch = np.concatenate(chunks)[:n_sample]
    return batch, traits


def action_probabilities(policy) -> Callable[[np.ndarray], np.ndarray]:
    """``obs (M, obs_dim) -> (M, N_ACTIONS)`` action probabilities from the policy's own log-probability vector."""
    def fn(obs: np.ndarray) -> np.ndarray:
        _, log_probs = policy.act(np.asarray(obs, dtype=np.float32), None)
        return np.exp(np.asarray(log_probs, dtype=np.float64))
    return fn


# ---------------------------------------------------------------------------------------------- manifest
def load_manifest(run_dir: Path) -> dict[str, Any]:
    path = run_dir / "eval" / "manifest.json"
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {"passes": {}}


def save_manifest(run_dir: Path, manifest: dict[str, Any]) -> None:
    path = run_dir / "eval" / "manifest.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    manifest.setdefault("run_dir", str(run_dir))
    manifest["written_utc"] = utc_now()
    path.write_text(json.dumps(manifest, indent=2, default=str))


def pass_done(manifest: dict[str, Any], key: str, files: Sequence[Path]) -> bool:
    entry = manifest.get("passes", {}).get(key)
    return bool(entry and entry.get("status") == "complete" and all(Path(f).exists() for f in files))


def record(manifest: dict[str, Any], key: str, **fields: Any) -> None:
    manifest.setdefault("passes", {})[key] = {**fields, "git": git_provenance(), "finished_utc": utc_now(), "status": "complete"}


# ---------------------------------------------------------------------------------------------- runs
def finished_runs(root: Path, conditions: Optional[Sequence[str]], seeds: Optional[Sequence[int]]) -> list[Path]:
    dirs = sorted(p.parent for p in root.glob("*/seed*/selection.json"))
    if conditions:
        dirs = [d for d in dirs if d.parent.name in set(conditions)]
    if seeds is not None:
        dirs = [d for d in dirs if int(d.name.removeprefix("seed")) in set(seeds)]
    return dirs


def run_config(run_dir: Path) -> HamletConfig:
    """The HamletConfig the run trained with, from its metadata.json."""
    meta = json.loads((run_dir / "metadata.json").read_text())
    raw = meta["hamlet_config"]
    fields = set(HamletConfig.__dataclass_fields__)
    cfg = HamletConfig(**{k: v for k, v in raw.items() if k in fields})
    for name in ("job_open", "market_open", "night"):
        value = getattr(cfg, name, None)
        if isinstance(value, list):
            setattr(cfg, name, tuple(value))
    cfg.validate()
    return cfg


def selected_checkpoint(run_dir: Path) -> Path:
    selection = json.loads((run_dir / "selection.json").read_text())
    if not selection.get("selected"):
        raise RuntimeError(f"{run_dir}: selection.json names no checkpoint")
    path = Path(selection["selected"])
    if not path.exists():
        path = run_dir / Path(selection["selected"]).name
    return path


def expected_files(out_dir: Path, condition: str, label: str, seeds: Sequence[int]) -> list[Path]:
    return [episode_path(out_dir, condition, label, s, 0) for s in seeds]


# ---------------------------------------------------------------------------------------------- passes
def pass_stochastic(run_dir: Path, cfg: HamletConfig, ckpt: Path, seeds: Sequence[int], manifest: dict, force: bool) -> int:
    policy, label = make_policy(fallback=str(ckpt))
    out = run_dir / "eval" / "stochastic"
    files = expected_files(out, cfg.condition_name, label, seeds)
    if not force and pass_done(manifest, "stochastic", files):
        return 0
    paths = evaluate(cfg, policy, seeds, out, checkpoint=label, overwrite=force)
    record(manifest, "stochastic", mode="stochastic", seeds=list(seeds), checkpoint=str(ckpt), condition=cfg.condition_name,
           scope="plan", out_dir=str(out), n_files=len(paths))
    return len(paths)


EVALUATE_HAS_MODE = "mode" in inspect.signature(evaluate).parameters


def pass_argmax(run_dir: Path, cfg: HamletConfig, ckpt: Path, seeds: Sequence[int], manifest: dict, force: bool) -> int:
    inner, label = make_policy(fallback=str(ckpt))
    out = run_dir / "eval" / "argmax"
    tag = f"{label}_argmax"
    files = expected_files(out, cfg.condition_name, tag, seeds)
    if not force and pass_done(manifest, "argmax", files):
        return 0
    if EVALUATE_HAS_MODE:       # the evaluation path's own mode (hamlet.evaluate.rollout mode="argmax")
        paths = evaluate(cfg, inner, seeds, out, checkpoint=tag, overwrite=force, mode="argmax")
        how = "hamlet.evaluate mode='argmax'"
    else:                       # the same computation as a wrapper, for a tree where the edit is not applied
        paths = evaluate(cfg, ArgmaxPolicy(inner), seeds, out, checkpoint=tag, overwrite=force)
        how = "ArgmaxPolicy wrapper (argmax of the policy's log-probability vector)"
    record(manifest, "argmax", mode="argmax", seeds=list(seeds), checkpoint=str(ckpt), condition=cfg.condition_name,
           scope="plan", out_dir=str(out), n_files=len(paths), implementation=how)
    return len(paths)


def pass_shocks(run_dir: Path, cfg: HamletConfig, ckpt: Path, seeds: Sequence[int], manifest: dict, force: bool) -> int:
    policy, label = make_policy(fallback=str(ckpt))
    total = 0
    scope = "plan" if cfg.arm in SHOCK_PLAN_ARMS else "superset"
    for shock in SHOCKS:
        shocked = dataclasses.replace(cfg, shock=shock)
        out = run_dir / "eval" / f"shock_{shock}"
        files = expected_files(out, shocked.condition_name, label, seeds)
        key = f"shock_{shock}"
        if not force and pass_done(manifest, key, files):
            continue
        paths = evaluate(shocked, policy, seeds, out, checkpoint=label, overwrite=force)
        record(manifest, key, mode="stochastic", shock=shock, seeds=list(seeds), checkpoint=str(ckpt),
               condition=shocked.condition_name, control="stochastic pass, same evaluation seed", scope=scope,
               out_dir=str(out), n_files=len(paths))
        total += len(paths)
    return total


def pass_init(run_dir: Path, cfg: HamletConfig, ckpt: Path, seeds: Sequence[int], manifest: dict, force: bool) -> int:
    if cfg.condition_name not in INIT_CONDITIONS:
        return 0
    policy, label = make_policy(fallback=str(ckpt))
    total = 0
    for name, rng in INIT_RANGES.items():
        cond = f"{cfg.condition_name}-init_{name}"
        out = run_dir / "eval" / f"init_{name}"
        files = expected_files(out, cond, label, seeds)
        key = f"init_{name}"
        if not force and pass_done(manifest, key, files):
            continue
        paths = evaluate(cfg, policy, seeds, out, checkpoint=label, condition=cond, init_range=rng, overwrite=force)
        record(manifest, key, mode="stochastic", init_range=list(rng), seeds=list(seeds), checkpoint=str(ckpt), condition=cond,
               scope="plan", out_dir=str(out), n_files=len(paths), default_is="the stochastic pass (0.50, 1.00)")
        total += len(paths)
    return total


def pass_swap(run_dir: Path, cfg: HamletConfig, ckpt: Path, seeds: Sequence[int], manifest: dict, force: bool,
              n_boot: int, replay_perm: int, replay_seeds: int) -> int:
    if cfg.symmetry != "S1":
        return 0
    out = run_dir / "eval" / "swap"
    swap_path, replay_path = out / "swap.json", out / "trait_home_shuffle.npz"
    seed = int(run_dir.name.removeprefix("seed"))
    done = 0
    if force or not pass_done(manifest, "swap", [swap_path]):
        policy, label = make_policy(fallback=str(ckpt))
        rng = np.random.default_rng([seed, SWAP_STREAM])
        batch, traits = observation_batch(cfg, policy, seeds, rng)
        fn = action_probabilities(policy)
        result: dict[str, Any] = {"n_observations": int(batch.shape[0]), "n_boot": int(n_boot), "kinds": {}}
        for kind in SWAP_KINDS:
            value, matrix = swap_test(fn, batch, cfg.N, swap=kind, trait_vectors=traits, return_matrix=True)
            draws = np.empty(n_boot)
            for b in range(n_boot):
                idx = rng.integers(0, batch.shape[0], size=batch.shape[0])
                draws[b] = swap_test(fn, batch[idx], cfg.N, swap=kind, trait_vectors=traits)
            lo, hi = np.quantile(draws, [DEFAULTS.alpha / 2, 1 - DEFAULTS.alpha / 2]) if n_boot else (np.nan, np.nan)
            result["kinds"][kind] = {"mean_jsd": float(value), "ci_low": float(lo), "ci_high": float(hi), "matrix": matrix.tolist()}
        out.mkdir(parents=True, exist_ok=True)
        swap_path.write_text(json.dumps(result, indent=2))
        record(manifest, "swap", mode="swap", seeds=list(seeds), checkpoint=str(ckpt), condition=cfg.condition_name, scope="plan",
               kinds=list(SWAP_KINDS), n_observations=int(batch.shape[0]), n_boot=int(n_boot), out_dir=str(out), n_files=1)
        done += 1
    if replay_perm > 0 and (force or not pass_done(manifest, "trait_home_shuffle", [replay_path])):
        policy, label = make_policy(fallback=str(ckpt))
        rng = np.random.default_rng([seed, REPLAY_STREAM])
        use = list(seeds)[:replay_seeds]
        counts = {f"seed{s}": np.stack(trait_and_home_shuffle_counts(cfg, lambda: policy, s, replay_perm, rng)) for s in use}
        out.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(replay_path, **counts)
        record(manifest, "trait_home_shuffle", mode="replay", seeds=use, n_perm=int(replay_perm), checkpoint=str(ckpt),
               condition=cfg.condition_name, scope="replay-only null of DOL_indiv", out_dir=str(out), n_files=1)
        done += 1
    return done


def greedy_shock_reference(root: Path, seeds: Sequence[int], force: bool) -> int:
    """GREEDY-CLOCK under each shock on the evaluation seeds, into ``<root>/A-S1-N<N>-<shock>/GREEDY-CLOCK/``."""
    total = 0
    for shock in SHOCKS:
        cfg = HamletConfig(shock=shock)
        paths = evaluate(cfg, GreedyClockPolicy(), seeds, root, checkpoint=NO_CHECKPOINT, overwrite=force)
        total += len(paths)
    return total


# ---------------------------------------------------------------------------------------------- one run
def run_passes(job) -> list[str]:
    """Every requested pass for one run directory; returns the log lines (one per pass)."""
    run_dir, passes, seeds, force, swap_boot, replay_perm, replay_seeds, threads = job
    try:
        import torch

        torch.set_num_threads(max(1, int(threads)))       # no oversubscription under --jobs
    except ImportError:
        pass
    cfg = run_config(run_dir)
    ckpt = selected_checkpoint(run_dir)
    manifest = load_manifest(run_dir)
    manifest.update({"condition": cfg.condition_name, "seed": int(run_dir.name.removeprefix("seed")),
                     "checkpoint": str(ckpt), "hamlet_config": json.loads(cfg.to_json())})
    lines = []
    for name in passes:
        t0 = time.perf_counter()
        if name == "stochastic":
            n = pass_stochastic(run_dir, cfg, ckpt, seeds, manifest, force)
        elif name == "argmax":
            n = pass_argmax(run_dir, cfg, ckpt, seeds, manifest, force)
        elif name == "shocks":
            n = pass_shocks(run_dir, cfg, ckpt, seeds, manifest, force)
        elif name == "init":
            n = pass_init(run_dir, cfg, ckpt, seeds, manifest, force)
        else:
            n = pass_swap(run_dir, cfg, ckpt, seeds, manifest, force, swap_boot, replay_perm, replay_seeds)
        save_manifest(run_dir, manifest)
        lines.append(f"{cfg.condition_name} seed {manifest['seed']} {name:10s} {'skip (complete)' if n == 0 else f'{n} file(s)'} "
                     f"{time.perf_counter() - t0:.1f} s")
    return lines


# ---------------------------------------------------------------------------------------------- main
def main(argv: Optional[Sequence[str]] = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", default="runs")
    parser.add_argument("--passes", nargs="+", default=["all"], choices=["all", *PASSES])
    parser.add_argument("--conditions", nargs="+", default=None, help="condition names, e.g. A-S1-N9")
    parser.add_argument("--seeds", type=int, nargs="+", default=None, help="training seeds")
    parser.add_argument("--n-eval-seeds", type=int, default=32)
    parser.add_argument("--swap-boot", type=int, default=DEFAULTS.n_boot, help="bootstrap draws over observations for the swap test")
    parser.add_argument("--replay-perm", type=int, default=20, help="trait_and_home_shuffle replays per evaluation seed (full rollouts; 0 skips)")
    parser.add_argument("--replay-seeds", type=int, default=8, help="how many evaluation seeds get replay counts")
    parser.add_argument("--no-greedy-shocks", action="store_true", help="skip the GREEDY-CLOCK shock reference")
    parser.add_argument("--force", action="store_true", help="redo passes even when the manifest says complete")
    parser.add_argument("--jobs", type=int, default=1, help="runs evaluated in parallel processes (keep 1 while a grid trains)")
    args = parser.parse_args(argv)

    root = Path(args.root)
    global INIT_CONDITIONS
    n = K.root_n_agents(root)
    INIT_CONDITIONS = (f"A-S0-N{n}", f"A-S1-N{n}")
    passes = list(PASSES) if "all" in args.passes else list(args.passes)
    seeds = evaluation_seeds(args.n_eval_seeds)
    dirs = finished_runs(root, args.conditions, args.seeds)
    if not dirs:
        print(f"no finished runs (selection.json) under {root}")
        return
    print(f"{len(dirs)} run(s), passes {passes}, {len(seeds)} evaluation seeds, git {git_provenance()['describe']}, {args.jobs} process(es)")
    threads = max(1, (os.cpu_count() or 1) // max(1, args.jobs))
    jobs = [(run_dir, passes, seeds, args.force, args.swap_boot, args.replay_perm, args.replay_seeds, threads) for run_dir in dirs]
    if args.jobs > 1:
        from concurrent.futures import ProcessPoolExecutor

        with ProcessPoolExecutor(max_workers=args.jobs) as pool:
            for lines in pool.map(run_passes, jobs):
                print("\n".join(lines), flush=True)
    else:
        for job in jobs:
            print("\n".join(run_passes(job)), flush=True)
    if "shocks" in passes and not args.no_greedy_shocks:
        t0 = time.perf_counter()
        n = greedy_shock_reference(root, seeds, args.force)
        print(f"GREEDY-CLOCK shock reference: {n} file(s) present under {root} ({time.perf_counter() - t0:.1f} s)")


if __name__ == "__main__":
    main()
